version: '3.7'
services:
  backend:
    build: chess-service
    ports:
      - "8080:8080"
    networks:
      - backend
      - db
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: chess-service-frontend
    ports:
      - "4200:80"
    networks:
      - backend

  postgres:
    image: postgres
    restart: always
    healthcheck:
      test: pg_isready -U postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - db

networks:
  db:
  backend:

